// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUer = `-- name: CreateUer :one
INSERT INTO "users" (
    "id", "created_at", "updated_at", "email"
) VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, email
`

func (q *Queries) CreateUer(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUer, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
